# Generated by Django 4.2.30 on 2026-09-24 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def make_adapt_private(apps, schema_editor):
    """ADAPT access now comes only from FolderGrant. Older ADAPT rows were created public."""
    for name in ('Folder', 'File'):
        model = apps.get_model('filemanager', name)
        model.objects.filter(third_party_source='adapt', is_public=True).update(is_public=False)


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('filemanager', '0014_folder_cached_total_file_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FolderGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_write', models.BooleanField(default=False, help_text='Also allow uploads and changes. Has no effect while the share is mounted read-only.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='filemanager.folder')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folder_grants', to='auth.group')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folder_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['folder__name'],
            },
        ),
        migrations.AddConstraint(
            model_name='foldergrant',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('group__isnull', True), ('user__isnull', False)), models.Q(('group__isnull', False), ('user__isnull', True)), _connector='OR'), name='foldergrant_user_xor_group', violation_error_message='Choose a user or a group, not both and not neither.'),
        ),
        migrations.AddConstraint(
            model_name='foldergrant',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('folder', 'user'), name='foldergrant_unique_user', violation_error_message='This user already has a grant on this folder. Edit that grant instead.'),
        ),
        migrations.AddConstraint(
            model_name='foldergrant',
            constraint=models.UniqueConstraint(condition=models.Q(('group__isnull', False)), fields=('folder', 'group'), name='foldergrant_unique_group', violation_error_message='This group already has a grant on this folder. Edit that grant instead.'),
        ),
        migrations.RunPython(make_adapt_private, migrations.RunPython.noop),
    ]
