# Generated by Django 4.2.30 on 2026-09-22 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('filemanager', '0014_folder_cached_total_file_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FolderAcl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptor', models.BinaryField(help_text='Self-relative SECURITY_DESCRIPTOR (owner, group, DACL)')),
                ('owner_sid', models.CharField(blank=True, max_length=190)),
                ('ace_count', models.PositiveIntegerField(default=0)),
                ('fetched_at', models.DateTimeField()),
                ('error', models.TextField(blank=True, help_text='Last fetch error, empty when the descriptor is current')),
                ('folder', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acl', to='filemanager.folder')),
            ],
            options={
                'verbose_name': 'ADAPT folder ACL',
                'verbose_name_plural': 'ADAPT folder ACLs',
            },
        ),
        migrations.CreateModel(
            name='DirectoryIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dn', models.CharField(blank=True, help_text='Distinguished name in the directory', max_length=512)),
                ('sid', models.CharField(blank=True, help_text='objectSid', max_length=190)),
                ('group_sids', models.JSONField(default=list, help_text='tokenGroups, as S-1-... strings')),
                ('fetched_at', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='directory_identity', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'directory identity',
                'verbose_name_plural': 'directory identities',
            },
        ),
    ]
