# Generated by Django 4.2.30 on 2026-09-25 05:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('filemanager', '0015_folder_grants'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nuid', models.CharField(blank=True, help_text='University of Nebraska ID, 8 digits. Set by adapt_users load.', max_length=8, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{8}$', 'A NUID is 8 digits, leading zeros included.')], verbose_name='NUID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
