# Generated by Django 4.2.30 on 2026-09-25 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0016_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='Send this user to the change password form until they choose a new password. Set for accounts adapt_users load creates; cleared when the user changes it.'),
        ),
    ]
