# Generated by Django 4.2.30 on 2026-09-25 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('filemanager', '0017_user_profile_must_change_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='RosterGroup',
            fields=[
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='roster', serialize=False, to='auth.group')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
